// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/google/wire"
	"go-web-demo/go/controller"
	"go-web-demo/go/dal/mapper"
	"go-web-demo/go/dal/mapper/mapperimpl"
	"go-web-demo/go/db"
	"go-web-demo/go/service"
	"go-web-demo/go/service/serviceimpl"
)

// Injectors from wire.go:

func InitUserController() controller.UserController {
	gormDB := db.NewSqlSession()
	userMapperImpl := &mapperimpl.UserMapperImpl{
		SqlSession: gormDB,
	}
	userServiceImpl := &serviceimpl.UserServiceImpl{
		UserMapper: userMapperImpl,
	}
	userController := controller.UserController{
		UserService: userServiceImpl,
	}
	return userController
}

// wire.go:

var MyProviderSet = wire.NewSet(db.NewSqlSession, wire.Struct(new(mapperimpl.UserMapperImpl), "*"), wire.Bind(new(mapper.UserMapper), new(*mapperimpl.UserMapperImpl)), wire.Struct(new(serviceimpl.UserServiceImpl), "*"), wire.Bind(new(service.UserService), new(*serviceimpl.UserServiceImpl)), wire.Struct(new(controller.UserController), "*"))
