// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"go-web-demo/go/controller"
	"go-web-demo/go/dal/mapper"
	"go-web-demo/go/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserController(db *gorm.DB) controller.UserController {
	userMapper := mapper.NewUserMapper(db)
	userService := service.NewUserService(userMapper)
	userController := controller.NewUserController(userService)
	return userController
}
