// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"go-web-demo/src/controller"
	"go-web-demo/src/dal"
	"go-web-demo/src/db"
	"go-web-demo/src/service"
)

// Injectors from wire.go:

func NewUserController() controller.UserController {
	gormDB := db.NewSqlSession()
	userMapperImpl := &dal.UserMapperImpl{
		SqlSession: gormDB,
	}
	userServiceImpl := &service.UserServiceImpl{
		UserMapper: userMapperImpl,
	}
	userController := controller.UserController{
		UserService: userServiceImpl,
	}
	return userController
}

// wire.go:

var MyProviderSet = wire.NewSet(db.NewSqlSession, wire.Struct(new(dal.UserMapperImpl), "*"), wire.Bind(new(dal.UserMapper), new(*dal.UserMapperImpl)), wire.Struct(new(service.UserServiceImpl), "*"), wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), wire.Struct(new(controller.UserController), "*"))
